#!/bin/sh

######
## Ruben's Hugo Post Install Script of Doom
## April 2015

set -e

_rsync='/usr/local/bin/rsync'
_server='chitanda'
_virtual_root='rubenerdcom'

echo '☕  Building/verifying empty directories Hugo needs...'
[ ! -d ./archetypes ] && mkdir ./archetypes
[ ! -d ./data ] && mkdir ./data

echo '☕  Removing previously generated content (if any)...'
rm -rf ./public/*

echo '☕  Print out latest podcast episode to sidebar...'
./scripts/latest-episode.sh
git add ./layouts/partials sidebar.html
git commit -m 'updated with latest episode'

echo '☕  Building site with Hugo (may take a few moments)...'
hugo

echo '☕  Moving podcast feed to /show/feed/...'
mkdir -p ./public/show/feed/
mv -f ./public/categories/show/index.xml ./public/show/feed/

echo '☕  Moving RSS feed from index.xml to /feed/...'
mkdir ./public/feed/
mv -f ./public/index.xml ./public/feed/index.xml

## echo '☕  Move Whole Wheat Radio feed so is not deleted...'
## mv -f ./public/tags/whole-wheat-radio/index.xml 

echo '☕  Removing all other generated feeds...'
rm -rf ./public/categories/*/index.xml
rm -rf ./public/tags/*/index.xml

echo '☕  Removing /categories/ from permalink, and /tags/ --> /tag/...'
rm -rf ./public/categories/index.*
mv -f ./public/categories/show/* ./public/show/
rm -rf ./public/categories/show/
mv -f ./public/categories/* ./public/
mv -f ./public/tags/ ./public/tag/

echo '☕  Fixing category and tag URLs in generated pages (may take a few moments)...'
for _post in ./public/*/*\.html; do
    sed -i '' -e 's/\/categories\//\//g' ${_post}
    sed -i '' -e 's/\/tags\//\/tag\//g' ${_post}
done

echo '☕  Compressing (with rsync -z) and pushing to server...'
${_rsync} --recursive --verbose --times --compress --rsh=ssh --checksum --delete \
    ./public/ ${_server}:${_virtual_root}/

echo '☕  Site changes now LIVE.'

