#!/bin/sh

######
## Ruben's Hugo Preview Script of Doom
## April 2015

set -e

echo '☕  Removing previously generated content (if any)...'
rm -rf ./public/*

echo '☕  Building local preview with Hugo (may take a few moments)...'
hugo server --watch
